name: india
description: "Damndeal India"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  shared_preferences: ^2.3.3
  lottie: ^3.3.1
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  phonepe_payment_sdk: ^3.0.0
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  webview_flutter: ^4.11.0
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  flutter_html: ^3.0.0
  cached_network_image: ^3.4.1
  http: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Damndeall.png"
  remove_alpha_ios: true
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/dth/
    - assets/images/shop/
    - assets/json/
    - assets/gifs/
    - assets/icons/
    - assets/icons/metro/
    - assets/images/mobile/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
